"""Every generated file is registered, headed, merge=regen, and current.

WHY (repo-body-plan I-11, 2026-10-07). Generated files were known in three
places that disagreed: Bone's MACHINE_WRITTEN dict (11 paths), .gitattributes
(2) and the --check of each writer (run by hand). state/generated.yml is now
the one registry; Bone reads it and this gate holds the rest to it. A
hand-edited artifact goes red here through its writer's own --check.
"""
from __future__ import annotations

import json
import pathlib
import re
import subprocess
import sys

import pytest
import yaml

REPO = pathlib.Path(__file__).resolve().parents[2]
REGISTRY = yaml.safe_load((REPO / "state/generated.yml").read_text(encoding="utf-8"))
FILES: dict[str, dict] = REGISTRY["files"]
CHECKS = sorted({tuple(e["check"]) for e in FILES.values() if e.get("check")})
AUTHORED = ["state/night-watch.json"]  # ADR 0002: merged, never regenerated
HEAD = re.compile(r"GENERATED by (\S+)")
HEAD_SKIP = ("docs/devlog/", "docs/archive/", "files/anatomy/wing/vendor/")


def _tracked() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True)
    return out.stdout.split()


def _head(path: pathlib.Path) -> str:
    with path.open(encoding="utf-8", errors="replace") as fh:
        return "".join(fh.readline() for _ in range(5))


def _headed(rel: str, writer: str) -> bool:
    p = REPO / rel
    if writer in HEAD.findall(_head(p)):
        return True
    if p.suffix == ".json":
        return json.loads(p.read_text(encoding="utf-8")).get("generated_by") == writer
    return False


def test_every_entry_names_a_writer_and_exists():
    assert len(FILES) >= 13
    bad = [p for p, e in FILES.items() if not e.get("writer") or not (REPO / p).is_file()]
    assert not bad, f"registry entries with no writer or no file: {bad}"
    unexplained = [p for p, e in FILES.items()
                   if (e.get("header") is False and not e.get("why"))
                   or (not e.get("check") and not e.get("checked_by"))]
    assert not unexplained, f"header: false needs `why`; no check needs `checked_by`: {unexplained}"


def test_every_entry_carries_the_header():
    missing = [p for p, e in FILES.items()
               if e.get("header", True) and not _headed(p, e["writer"])]
    assert not missing, f"no `GENERATED by <writer>` header (or JSON generated_by): {missing}"


def test_every_headed_file_is_registered():
    """The converse: a file that says it is generated is in the registry."""
    found = []
    for rel in _tracked():
        p = REPO / rel
        if rel.startswith(HEAD_SKIP) or "/node_modules/" in rel or not p.is_file() or p.is_symlink():
            continue
        if HEAD.search(_head(p)) and rel not in FILES:
            found.append(rel)
    assert not found, f"files headed GENERATED by but not in state/generated.yml: {found}"


def _merge_attr(paths: list[str]) -> dict[str, str]:
    out = subprocess.run(["git", "check-attr", "merge", "--", *paths],
                         cwd=REPO, capture_output=True, text=True, check=True).stdout
    return {line.split(": ")[0]: line.rsplit(": ", 1)[-1] for line in out.splitlines()}


def test_registry_and_merge_regen_are_one_list():
    attrs = _merge_attr(list(FILES) + AUTHORED)
    not_regen = [p for p in FILES if attrs.get(p) != "regen"]
    assert not not_regen, f"registered but not merge=regen in .gitattributes: {not_regen}"
    assert all(attrs[p] != "regen" for p in AUTHORED), "authored state swept into regen"
    lines = (REPO / ".gitattributes").read_text(encoding="utf-8").splitlines()
    regen = [ln.split()[0] for ln in lines if ln.strip() and not ln.startswith("#")
             and "merge=regen" in ln]
    assert set(regen) <= set(FILES), f"merge=regen but not registered: {set(regen) - set(FILES)}"


@pytest.mark.parametrize("argv", CHECKS, ids=[" ".join(c) for c in CHECKS])
def test_the_artifact_is_what_its_writer_writes(argv):
    got = subprocess.run([sys.executable, *argv], cwd=REPO, capture_output=True,
                         text=True, timeout=600)
    assert got.returncode == 0, (
        f"{' '.join(argv)} says the committed file is not what it writes — rerun the "
        f"writer, never edit the file:\n{(got.stdout + got.stderr)[-1500:]}")
