"""Anatomy gate — a `native_oidc` service must not be BROKEN by absent Authentik.

`roles/pazny.traefik/vars/main.yml` marks 20 services `oidc`, and the Authentik
preflight in `main.yml` deliberately does NOT refuse for them: the doctrine is
that with `install_authentik: false` they render no OIDC configuration and fall
back to their own login — degraded, not broken. That doctrine was stated after
checking three of the twenty. A sweep of the other seventeen (2026-09-01) found
two that break it, and this pins both.

  * **superset** — `superset_config.py.j2` pinned `AUTH_TYPE = AUTH_OAUTH`
    unconditionally, so Flask-AppBuilder served the OAuth provider page instead
    of the password form. Not "its own login": NO working UI login at all, only
    the `provider: db` API path `roles/pazny.superset/tasks/post.yml:66` uses.
  * **nextcloud** — six steps of `nextcloud-base/hooks/post_compose.yml` gated
    only on the container being up, so a converge with Authentik off installed
    `user_oidc`, flipped `allow_local_remote_servers`, and registered a
    provider pointing at a dead discovery URI. The role-side equivalent IS
    gated (`tasks/stacks/stack-up.yml:429`); the plugin hook was a divergent
    duplicate that lost the guard. Every sibling hook has it —
    `gitea-base/hooks/post_compose.yml:73`, `wordpress-base/…:78`.

WHAT THIS DOES NOT COVER, and it is the larger half. Seventeen other `oidc`
services are verified by hand-audit only, not by a gate. Two known-unfixable
findings from the same sweep are left as doctrine, deliberately:

  * **outline has no local login at all.** Its guard is present and correct
    (`outline-base.compose.yml.j2:28`), and that is precisely the problem —
    guarded, Outline starts with no auth provider whatsoever and cannot be used.
    No guard can fix that; it needs a decision about whether
    `install_authentik: false` may enable Outline at all.
  * **woodpecker is classified `oidc` but its plugin declares
    `mode: forward_auth`** (`woodpecker-base/plugin.yml:84`). It is gated by
    Gitea OAuth, not by Authentik, so absent Authentik costs it nothing — but
    the two declarations disagree and one of them is wrong.

CI-safe: renders one template with Ansible, parses one hook file. No estate.
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess
import tempfile

import pytest
import yaml

REPO = pathlib.Path(__file__).resolve().parents[2]
SUPERSET = REPO / "roles/pazny.superset/templates/superset_config.py.j2"
NEXTCLOUD_HOOK = REPO / "files/anatomy/plugins/nextcloud-base/hooks/post_compose.yml"

PROBE = """---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files: [default.config.yml]
  vars:
    # install_authentik is NOT set here: play `vars:` are precedence 14 and
    # `vars_files:` is 16, so default.config.yml's `true` would win. It is
    # passed as an extra-var (22) below instead.
    # Generated by the secrets registry at converge time, not by
    # default.config.yml. Stubbed so the probe measures the Authentik guard
    # rather than the absence of a runtime secret.
    nos_derived_secrets:
      superset: probe
      superset_secret: probe
      oidc_superset: probe
  tasks:
    - ansible.builtin.copy:
        dest: "{out}"
        content: "{{{{ lookup('template', playbook_dir ~ '/{tpl}') }}}}"
"""


def _render_without_authentik(template_relpath: str) -> str:
    if shutil.which("ansible-playbook") is None:
        pytest.skip("ansible-playbook unavailable in this lane")
    with tempfile.NamedTemporaryFile(suffix=".out", delete=False) as fh:
        out = pathlib.Path(fh.name)
    probe = REPO / f".oidc-degrade-probe-{out.stem}.yml"
    probe.write_text(PROBE.format(out=out, tpl=template_relpath))
    try:
        run = subprocess.run(["ansible-playbook", probe.name,
                              "-e", "install_authentik=false"], cwd=REPO,
                             capture_output=True, text=True, timeout=180)
        assert run.returncode == 0, (
            "the template does not even RENDER with install_authentik false — "
            f"that is a converge abort, not a degradation:\n{run.stdout}\n{run.stderr}")
        return out.read_text()
    finally:
        probe.unlink(missing_ok=True)
        out.unlink(missing_ok=True)


def test_superset_falls_back_to_its_own_login():
    rendered = _render_without_authentik(
        "roles/pazny.superset/templates/superset_config.py.j2")
    # The unused `from ... import AUTH_OAUTH` at the top is harmless; what
    # matters is whether the ASSIGNMENT renders.
    assert "AUTH_TYPE = AUTH_OAUTH" not in rendered, (
        "superset_config.py pins AUTH_TYPE = AUTH_OAUTH with no Authentik to "
        "talk to — FAB then serves the OAuth provider page and the operator "
        "has no UI login. Absent the guard, AUTH_DB is the correct fallback.")
    assert "OAUTH_PROVIDERS" not in rendered, (
        "an OAuth provider is declared against an Authentik that is not installed")


def test_superset_still_wires_oidc_when_authentik_is_present():
    """The guard must not have turned SSO off for the estates that have it."""
    body = SUPERSET.read_text()
    assert "AUTH_TYPE = AUTH_OAUTH" in body and "OAUTH_PROVIDERS" in body, (
        "the superset OIDC block was deleted rather than guarded")


def test_every_nextcloud_oidc_hook_step_is_gated():
    steps = []

    def walk(node):
        if isinstance(node, list):
            for item in node:
                if isinstance(item, dict) and "id" in item:
                    steps.append(item)
                else:
                    walk(item)
        elif isinstance(node, dict):
            for value in node.values():
                walk(value)

    walk(yaml.safe_load(NEXTCLOUD_HOOK.read_text()))
    assert steps, "the nextcloud post_compose hook declares no steps"

    # A step that configures OIDC is one whose command names it. `check_running`
    # is a read-only docker inspect and is deliberately ungated.
    oidc = [s for s in steps
            if "oidc" in str(s.get("cmd", "")).lower()
            or "authentik" in str(s.get("cmd", "")).lower()
            or "allow_local_remote_servers" in str(s.get("cmd", ""))]
    assert len(oidc) >= 6, (
        f"expected the six OIDC steps, matched {len(oidc)} — the detector or "
        "the hook changed shape")
    ungated = [s["id"] for s in oidc if "install_authentik" not in str(s.get("when", ""))]
    assert not ungated, (
        f"nextcloud hook steps configure OIDC with no install_authentik guard: "
        f"{ungated}. With Authentik off these register a provider pointing at a "
        f"dead discovery URI. Every sibling plugin hook carries the guard.")
