---
- name: Restart mcpo
  ansible.builtin.shell: |
    cd {{ stacks_dir }}/iiab
    {{ docker_bin }} compose -p iiab \
      -f docker-compose.yml \
      $(find overrides -name '*.yml' -exec echo '-f {}' \;) \
      restart mcpo mcp-grafana 2>&1 || true
  args:
    executable: /bin/bash
  failed_when: false
