#!/usr/bin/env python3
"""KEAP self-model generator — nOS architecture as a KEAP knowledge tree.

Writes ONE deterministic markdown dataPoint per nOS service (plus a per-stack card
and a platform-root card) into a class-2 *shared* tree:

    <out-root>/nOS/<stack>/<service>.md
    <out-root>/nOS/<stack>/_stack.md
    <out-root>/nOS/_platform.md

where <out-root> is the doctrine class-2 dir
`{nos_data_root}/tenants/<slug>/shared/nos-docs` (docs/doctrine/filesystem.md §class 2:
"app-managed multi-user content"). KEAP's server/fs-sync.ts (v1.7.0) mirrors the tree
into knowledge objects once it is bind-mounted under KEAP_USER_FILES_DIR and its top
class dir ("nOS") is listed in KEAP_FS_SYNC_DIRS.

Design + KEAP-contract analysis: docs/archive/keap-selfmodel.md.

Why a generator (not a pure Jinja template): the file bodies carry real taxonomy
node-ids (server/objects.ts classifyRef → anchor rays) sourced from a category map,
plus a multi-source join (state/manifest.yml spine ⋈ per-plugin display name +
description), plus compare-and-skip idempotency so an unchanged catalog rewrites
nothing (fs-sync skips on unchanged size+mtime — no re-embed storm). All of that is
awkward in Jinja and trivially unit-testable here.

REAL per-service state (operator refinement 2026-07-18): each card carries the
service's ACTUAL deployed facts — version, image, port, domain, data path, mem/cpu
limits — NOT generic prose. Those values are Jinja-only resolvable (e.g.
`{{ gitea_domain | default('git' ~ …) }}`), so the keap role's tasks/selfmodel.yml
resolves them in Ansible via `lookup('vars', <manifest var name>)` — keyed off the
manifest's own `version_var`/`port_var`/`domain_var`/`data_path_var` declarations
(role-adjacent, no naming-convention guessing) — and passes them here as --facts-json.
The generator embeds them into the card body (→ embedded → semantic-searchable), so the
tree reflects the REAL playbook state, not a static description.

Determinism: content is fully sorted, carries no timestamps/random; the facts are
resolved config values (pinned versions, ports, domains), stable across runs. Re-running
against an unchanged manifest + facts writes zero bytes.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

# ── taxonomy anchors (KEAP src/game/data/taxonomy.ts, Computer Science branch) ──────
# Every card anchors to the CS root (whole-constellation ray) plus one category ray.
# Ids are dotted 2-digit — server/objects.ts classifyRef promotes [[NN.NN]] to a
# taxonomy-node anchor iff getNode(id) exists (all ids below are real v1.7.0 nodes).
CS_ROOT = "02.02"  # Computer Science
ANCHOR_BY_CATEGORY = {
    "database": "02.02.05",          # Databases
    "cache": "02.02.05.02",          # NoSQL Databases
    "identity": "02.02.08",          # Computer Security
    "secrets": "02.02.08",           # Computer Security
    "proxy": "02.02.07",             # Computer Networks
    "vpn": "02.02.07",               # Computer Networks
    "observability": "02.04",        # Information Theory (metrics/telemetry)
    "monitoring": "02.04",           # Information Theory
    "ci": "02.02.04",                # Software Engineering
    "devops": "02.02.04",            # Software Engineering
    "git": "02.02.04",               # Software Engineering
    "ai": "02.02.09",                # Artificial Intelligence
    "automation": "02.02.09",        # Artificial Intelligence
    "web": "02.02.07.04",            # Web Technologies
    "cms": "02.02.07.04",            # Web Technologies
    "content": "02.02.07.04",        # Web Technologies
    "storage": "02.02.06",           # Operating Systems (filesystems)
}
# Per-stack fallback anchor when the manifest category doesn't map above.
ANCHOR_BY_STACK = {
    "infra": "02.02.06",             # Operating Systems (platform substrate)
    "observability": "02.04",        # Information Theory
    "devops": "02.02.04",            # Software Engineering
    "b2b": "02.02.07.04",            # Web Technologies
    "data": "02.02.05",              # Databases
    "iiab": "02.02.07.04",           # Web Technologies
    "engineering": "02.02",          # Computer Science (generic)
    "voip": "02.02.07",              # Computer Networks
    "host": "02.02.06",              # Operating Systems
}

HOST_STACK = "host"  # bucket for manifest services with stack: null (host-native)
GEN_MARKER = "<!-- nOS self-model — generated by keap_selfmodel_gen.py from state/manifest.yml (spine) + per-plugin manifests (prose) + Ansible-resolved role vars (real state). Deterministic; edit the source, not this file. -->"


def _norm(s: str) -> str:
    return re.sub(r"[_-]", "", (s or "").lower())


def load_plugins(plugins_dir: str) -> dict:
    """Map normalized service id → {name, description} from *-base plugin.yml."""
    import yaml

    out: dict[str, dict] = {}
    if not os.path.isdir(plugins_dir):
        return out
    for entry in sorted(os.listdir(plugins_dir)):
        if not entry.endswith("-base"):
            continue
        p = os.path.join(plugins_dir, entry, "plugin.yml")
        if not os.path.isfile(p):
            continue
        try:
            with open(p) as fh:
                y = yaml.safe_load(fh) or {}
        except Exception:
            continue
        ui = (y.get("ui-extension") or y.get("ui_extension") or {})
        hub = (ui.get("hub_card") or {})
        authentik = (y.get("authentik") or {})
        name = (hub.get("title") or authentik.get("name") or "").strip()
        desc = (hub.get("description") or "").strip()
        if not desc:
            # top-level description is a paragraph — take the first sentence/line.
            top = (y.get("description") or "").strip()
            desc = re.split(r"(?<=[.!?])\s|\n", top)[0].strip() if top else ""
        out[_norm(entry[:-5])] = {"name": name, "description": desc}
    return out


# Real-state facts we surface on a service card, in render order. Keys are the
# normalized fact names produced by tasks/selfmodel.yml (resolved from the
# manifest's *_var declarations); label is the card wording.
FACT_LABELS = [
    ("image", "Image"),
    ("version", "Version"),
    ("domain", "Domain"),
    ("port", "Port"),
    ("data_path", "Data path"),
    ("mem_limit", "Memory limit"),
    ("cpus", "CPU limit"),
]


def build_model(manifest_path: str, plugins_dir: str, deps: dict, anchors: dict,
                facts: dict | None = None) -> dict:
    """Return {'platform':..., 'stacks': {...}, 'services': {id: {...}}}.

    `facts` (from tasks/selfmodel.yml, keyed by service id) carries the REAL
    Ansible-resolved deployment values (version/image/port/domain/data_path/…).
    """
    import yaml

    facts = facts or {}
    with open(manifest_path) as fh:
        manifest = yaml.safe_load(fh) or {}
    plugins = load_plugins(plugins_dir)

    services: dict[str, dict] = {}
    for s in manifest.get("services", []):
        sid = s["id"]
        stack = s.get("stack") or HOST_STACK
        pj = plugins.get(_norm(sid), {})
        display = pj.get("name") or sid.replace("_", " ").replace("-", " ").title()
        # REAL facts for this service (empty strings/None dropped).
        sfacts = {k: str(v).strip() for k, v in (facts.get(sid) or {}).items()
                  if v not in (None, "", "None") and str(v).strip()}
        # Description = the plugin prose, appended with a real-state sentence so the
        # ACTUAL deployment (image:version, domain) lands in the embedded body.
        base_desc = pj.get("description") or (
            f"{display} — a {s.get('category') or 'platform'} service in the "
            f"nOS {stack} stack."
        )
        state_bits = []
        if sfacts.get("image"):
            iv = sfacts["image"] + (f":{sfacts['version']}" if sfacts.get("version") else "")
            state_bits.append(iv)
        elif sfacts.get("version"):
            state_bits.append(f"v{sfacts['version']}")
        if sfacts.get("domain"):
            state_bits.append(f"https://{sfacts['domain']}")
        description = base_desc + (
            f" Deployed as {', '.join(state_bits)}." if state_bits else ""
        )
        # Category anchor → stack anchor → CS root.
        cat = (s.get("category") or "").lower()
        anchor = (
            anchors.get(sid)
            or ANCHOR_BY_CATEGORY.get(cat)
            or ANCHOR_BY_STACK.get(stack)
            or CS_ROOT
        )
        # Dependencies: authentik for any SSO consumer, plus curated overrides.
        dep_set = set(deps.get(sid, []))
        if s.get("oidc") in ("native", "proxy") and sid != "authentik":
            dep_set.add("authentik")
        services[sid] = {
            "id": sid,
            "stack": stack,
            "display": display,
            "description": description,
            "category": s.get("category"),
            "tier": s.get("rbac_tier"),
            "oidc": s.get("oidc"),
            "domain_var": s.get("domain_var"),
            "anchor": anchor,
            "deps": sorted(dep_set),
            "facts": sfacts,
        }

    stacks: dict[str, list] = {}
    for sid, sv in services.items():
        stacks.setdefault(sv["stack"], []).append(sid)
    for st in stacks:
        stacks[st] = sorted(stacks[st])

    return {"stacks": stacks, "services": services}


# ── rendering ───────────────────────────────────────────────────────────────────

# relPath is uid-relative (what KEAP fs-sync hashes into the object id) — the
# top-class dir IS `nOS`, so the shape is <top>/<stack>/<service>.md.
def _relpath_service(top: str, stack: str, sid: str) -> str:
    return f"{top}/{stack}/{sid}.md"


def _relpath_stack(top: str, stack: str) -> str:
    return f"{top}/{stack}/_stack.md"


def _relpath_platform(top: str) -> str:
    return f"{top}/_platform.md"


def _obj_id(uid: str, relpath: str) -> str:
    import hashlib

    return f"fs:{uid}:{hashlib.sha1(relpath.encode('utf-8')).hexdigest()[:16]}"


def _wikilink(uid: str, relpath: str) -> str:
    return f"[[object:{_obj_id(uid, relpath)}]]"


def render_service(model: dict, sid: str, uid: str, top: str) -> str:
    sv = model["services"][sid]
    stack = sv["stack"]
    lines = [f"# {sv['display']}", "", sv["description"], ""]
    lines.append(f"- **Stack:** {stack}")
    if sv["tier"] is not None:
        lines.append(f"- **RBAC tier:** {sv['tier']}")
    if sv["category"]:
        lines.append(f"- **Category:** {sv['category']}")
    if sv["oidc"]:
        lines.append(f"- **SSO:** {sv['oidc']}")
    lines.append(f"- **nOS role:** pazny.{sid}")
    # REAL deployed state (Ansible-resolved facts) — only the ones present.
    state = [(label, sv["facts"][k]) for k, label in FACT_LABELS if sv["facts"].get(k)]
    if state:
        lines.append("")
        lines.append("## State")
        for label, val in state:
            lines.append(f"- **{label}:** {val}")
    lines.append("")
    lines.append("## Relations")
    # Taxonomy anchors (render as rays): whole-map CS root + a category node.
    anchors = [CS_ROOT]
    if sv["anchor"] != CS_ROOT:
        anchors.append(sv["anchor"])
    lines.append(
        "- topic anchors: " + " ".join(f"[[{a}]]" for a in anchors)
    )
    # belongs-to → its stack card (object cross-link, embeddable + forward-compat).
    lines.append(
        f"- belongs-to {_wikilink(uid, _relpath_stack(top, stack))} — "
        f"the **{stack}** stack"
    )
    for dep in sv["deps"]:
        if dep in model["services"]:
            dstack = model["services"][dep]["stack"]
            lines.append(
                f"- depends-on {_wikilink(uid, _relpath_service(top, dstack, dep))} "
                f"— {model['services'][dep]['display']}"
            )
    lines += ["", GEN_MARKER, ""]
    return "\n".join(lines)


def render_stack(model: dict, stack: str, uid: str, top: str) -> str:
    members = model["stacks"][stack]
    lines = [
        f"# nOS stack: {stack}",
        "",
        f"The **{stack}** compose stack of the nOS platform — "
        f"{len(members)} service(s): {', '.join(members)}.",
        "",
        "## Relations",
        f"- topic anchor: [[{CS_ROOT}]]",
        f"- part-of {_wikilink(uid, _relpath_platform(top))} — the nOS platform",
    ]
    for sid in members:
        lines.append(
            f"- contains {_wikilink(uid, _relpath_service(top, stack, sid))} "
            f"— {model['services'][sid]['display']}"
        )
    lines += ["", GEN_MARKER, ""]
    return "\n".join(lines)


def render_platform(model: dict, uid: str, top: str) -> str:
    stacks = sorted(model["stacks"])
    n_svc = len(model["services"])
    lines = [
        "# nOS — platform self-model",
        "",
        "nOS is an Ansible-provisioned self-hosted Agentic Home Lab: "
        f"{n_svc} services across {len(stacks)} stacks, all FOSS, all local. "
        "This constellation is the platform's model of its own architecture, "
        "generated from state/manifest.yml.",
        "",
        "## Relations",
        f"- topic anchor: [[{CS_ROOT}]]",
    ]
    for st in stacks:
        lines.append(
            f"- stack {_wikilink(uid, _relpath_stack(top, st))} — "
            f"**{st}** ({len(model['stacks'][st])} services)"
        )
    lines += ["", GEN_MARKER, ""]
    return "\n".join(lines)


# ── write with compare-and-skip + prune ───────────────────────────────────────────

def _write_if_changed(path: str, content: str, result: dict) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    data = content.encode("utf-8")
    if os.path.isfile(path):
        with open(path, "rb") as fh:
            if fh.read() == data:
                result["unchanged"] += 1
                return
        with open(path, "wb") as fh:
            fh.write(data)
        result["updated"] += 1
        return
    with open(path, "wb") as fh:
        fh.write(data)
    result["created"] += 1


def generate(model: dict, out_root: str, uid: str, top: str) -> dict:
    """Write the whole tree under <out_root>/nOS/, prune stale .md. Returns counts."""
    result = {"created": 0, "updated": 0, "unchanged": 0, "removed": 0}
    nos_root = os.path.join(out_root, top)
    wanted: set[str] = set()

    plat_path = os.path.join(out_root, _relpath_platform(top))
    _write_if_changed(plat_path, render_platform(model, uid, top), result)
    wanted.add(os.path.realpath(plat_path))

    for stack in sorted(model["stacks"]):
        sp = os.path.join(out_root, _relpath_stack(top, stack))
        _write_if_changed(sp, render_stack(model, stack, uid, top), result)
        wanted.add(os.path.realpath(sp))
        for sid in model["stacks"][stack]:
            fp = os.path.join(out_root, _relpath_service(top, stack, sid))
            _write_if_changed(fp, render_service(model, sid, uid, top), result)
            wanted.add(os.path.realpath(fp))

    # Prune stale generated cards (a removed service's card must disappear so
    # fs-sync prunes its object). Only touch .md under our own nOS/ subtree.
    for dirpath, _dirs, files in os.walk(nos_root):
        for f in files:
            if not f.endswith(".md"):
                continue
            full = os.path.join(dirpath, f)
            if os.path.realpath(full) not in wanted:
                os.remove(full)
                result["removed"] += 1

    return result


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate the KEAP nOS self-model tree.")
    ap.add_argument("--manifest", required=True, help="path to state/manifest.yml")
    ap.add_argument("--plugins-dir", required=True, help="files/anatomy/plugins")
    ap.add_argument("--out-root", required=True,
                    help="class-2 shared dir, e.g. .../shared/nos-docs")
    ap.add_argument("--uid", default="nos-docs",
                    help="KEAP fs-sync owner uid the tree mounts as (default nos-docs)")
    ap.add_argument("--top", default="nOS",
                    help="fs-sync top class dir under the uid (default nOS)")
    ap.add_argument("--deps-json", default="{}",
                    help="JSON map {service:[dep,...]} of extra dependency edges")
    ap.add_argument("--anchors-json", default="{}",
                    help="JSON map {service: 'NN.NN'} of per-service taxonomy anchors")
    ap.add_argument("--facts-json", default="{}",
                    help="JSON map {service: {version,image,port,domain,...}} of REAL "
                         "Ansible-resolved deployment facts (from tasks/selfmodel.yml)")
    args = ap.parse_args(argv)

    deps = json.loads(args.deps_json or "{}")
    anchors = json.loads(args.anchors_json or "{}")
    facts = json.loads(args.facts_json or "{}")
    model = build_model(args.manifest, args.plugins_dir, deps, anchors, facts)
    result = generate(model, args.out_root, args.uid, args.top)
    result["services"] = len(model["services"])
    result["stacks"] = len(model["stacks"])
    print(json.dumps(result))
    return 0


if __name__ == "__main__":
    sys.exit(main())
