"""Canonical GDPR Article-30 record mapper — single source of truth.

The nOS GDPR story has two surfaces that MUST agree:

  * the static **DPA register** (`state/dpa-register.md`, generated by
    `tools/gdpr-dpa-register.py`) — the auditable artifact an operator hands
    to a DPO; CI-rendered, no running Wing required.
  * the live **`gdpr_processing`** table behind Wing's `/gdpr` UI — populated
    at deploy time by `bin/upsert-gdpr.php`.

Both consume the same upstream source-of-truth: the per-plugin `gdpr:` block
(`files/anatomy/plugins/<svc>-base/plugin.yml`, loader-validated against
Article 6(1)) for Tier-1 core services, and the Tier-2 app manifests
(`apps/<name>.yml`). This module is the ONE place that turns a `gdpr:` block
into a complete Article-30 record — default-filling the columns the register
needs but a terse plugin block omits (`purpose`, `storage_location`,
`transfers_outside_eu`, `security_measures`). Keep the mapping here so the
markdown register and the SQLite register never drift.

Tier-1 prior gap (C3, 2026-05-25): plugin `gdpr:` blocks were *validated* by
the loader but never *ingested* — the live register + DPA story covered only
the 4 Tier-2 apps, not the ~50 core services. This module closes that.

Pure-Python, no Ansible imports, so it runs in CI and in a venv.
"""

from __future__ import annotations

import pathlib
from typing import Any

try:  # imported as module_utils.nos_gdpr (tests / tools with files/anatomy on path)
    from . import load_plugins
except ImportError:  # imported flat
    import load_plugins  # type: ignore


# Platform-wide technical + organizational measures (Article 32). Every nOS
# service inherits these unless its plugin overrides `gdpr.security_measures`.
# Authoritative prose lives in docs/security-baseline.md (the DPO one-pager).
PLATFORM_SECURITY_MEASURES: list[str] = [
    "TLS in transit (Traefik edge; wildcard cert)",
    "Authentik SSO + RBAC tier access control",
    "Secrets held in Infisical / launchd env, never plaintext at rest",
    "Disk encryption at rest is operator-provisioned (FileVault / LUKS)",
    "Self-hosted: no third-party data processor unless declared below",
]

# Article-30 record column order — mirrors wing.db `gdpr_processing` plus a few
# render-only extras (eu_residency, stack, tier, source_plugin). The upsert
# tool ignores keys it doesn't map, so the extras are harmless on ingest.
RECORD_COLUMNS = [
    "id", "name", "purpose", "legal_basis",
    "data_categories", "data_subjects", "processors", "security_measures",
    "retention_days", "transfers_outside_eu", "storage_location", "notes",
]


def _slug(plugin_name: str) -> str:
    """`nextcloud-base` -> `nextcloud`; leaves non-`-base` names untouched."""
    return plugin_name[:-5] if plugin_name.endswith("-base") else plugin_name


def _display(slug: str, override: str | None) -> str:
    if override:
        return override
    return slug.replace("-", " ").replace("_", " ").title()


def _retention_human(days: Any) -> str:
    """Render helper: GDPR retention horizon as prose for the DPA table."""
    if days is None:
        return "indefinite (unspecified — justify)"
    try:
        d = int(days)
    except (TypeError, ValueError):
        return str(days)
    if d < 0:
        return "indefinite (lifecycle-managed; deletion via DSAR)"
    if d == 0:
        return "transient (not persisted)"
    if d % 365 == 0:
        return f"{d} days (~{d // 365}y)"
    return f"{d} days"


def gdpr_block_to_record(
    gdpr: dict,
    *,
    record_id: str,
    slug: str,
    stack: str | None = None,
    tier: str = "core",
    display_name: str | None = None,
    source_plugin: str | None = None,
) -> dict:
    """Map ONE `gdpr:` block to a complete Article-30 record dict.

    Default-fills the register columns a terse block omits. `purpose_generated`
    flags rows whose purpose we synthesized (so a DPO review can prioritize
    filling them in upstream).
    """
    gdpr = gdpr or {}
    name = _display(slug, display_name or gdpr.get("name"))

    purpose = (gdpr.get("purpose") or "").strip()
    purpose_generated = not purpose
    if purpose_generated:
        purpose = (
            f"Operation of the {name} service within the nOS self-hosted "
            f"platform; processing limited to what the service requires to "
            f"function for authenticated users."
        )

    eu_residency = gdpr.get("eu_residency")
    if eu_residency is None:
        eu_residency = True  # all-local FOSS default
    if "transfers_outside_eu" in gdpr:
        transfers = 1 if gdpr["transfers_outside_eu"] else 0
    else:
        transfers = 0 if eu_residency else 1

    storage = gdpr.get("storage_location")
    if not storage:
        storage = (
            f"'{stack}' compose stack on host (Docker volumes)"
            if stack else "host service (non-Docker / launchd)"
        )

    measures = gdpr.get("security_measures")
    if not measures:
        measures = list(PLATFORM_SECURITY_MEASURES)

    return {
        "id": record_id,
        "name": name,
        "purpose": purpose,
        "legal_basis": gdpr.get("legal_basis", ""),
        "data_categories": list(gdpr.get("data_categories") or []),
        "data_subjects": list(gdpr.get("data_subjects") or []),
        "processors": list(gdpr.get("processors") or []),
        "security_measures": list(measures),
        "retention_days": gdpr.get("retention_days"),
        "transfers_outside_eu": transfers,
        "storage_location": storage,
        "notes": (gdpr.get("notes") or None),
        # ── render-only extras (not upserted) ──
        "eu_residency": bool(eu_residency),
        "stack": stack,
        "tier": tier,
        "source_plugin": source_plugin or slug,
        "purpose_generated": purpose_generated,
    }


def records_from_plugins(plugins_root: str | pathlib.Path) -> list[dict]:
    """Every Tier-1 plugin carrying a `gdpr:` block → Article-30 record.

    id convention: `svc_<slug>` (mirrors the `app_<name>` Tier-2 convention).
    """
    root = pathlib.Path(plugins_root)
    out: list[dict] = []
    for p in load_plugins.discover(root):
        gdpr = p.manifest.get("gdpr")
        if not gdpr:
            continue
        slug = _slug(p.name)
        out.append(
            gdpr_block_to_record(
                gdpr,
                record_id=f"svc_{slug}",
                slug=slug,
                stack=load_plugins._plugin_stack(p),
                tier="core",
                source_plugin=p.name,
            )
        )
    out.sort(key=lambda r: r["id"])
    return out


def records_from_app_manifests(apps_dir: str | pathlib.Path) -> list[dict]:
    """Tier-2 app manifests (`apps/<name>.yml`) → Article-30 records.

    id convention: `app_<name>` (matches `roles/pazny.apps_runner`).
    Skips templates (`_template.yml`) and `.draft` files (runner ignores them).
    """
    import yaml

    d = pathlib.Path(apps_dir)
    out: list[dict] = []
    if not d.is_dir():
        return out
    for f in sorted(d.glob("*.yml")):
        if f.name.startswith("_") or f.name.endswith(".draft"):
            continue
        try:
            m = yaml.safe_load(f.read_text()) or {}
        except yaml.YAMLError:
            continue
        if not isinstance(m, dict):
            continue
        gdpr = m.get("gdpr")
        if not gdpr:
            continue
        app_id = m.get("id") or m.get("name") or f.stem
        out.append(
            gdpr_block_to_record(
                gdpr,
                record_id=f"app_{app_id}",
                slug=str(app_id),
                stack="apps",
                tier="app",
                display_name=m.get("name"),
                source_plugin=f.name,
            )
        )
    out.sort(key=lambda r: r["id"])
    return out


def records_from_agents(agents_dir: str | pathlib.Path) -> list[dict]:
    """Agent ceremonies (`files/anatomy/agents/<name>/agent.yml`) → records.

    WHY THIS SWEEP EXISTS (2026-08-13). `all_records()` read plugins and app
    manifests, and the agent definitions live in neither — so the register
    could be complete, pass its coverage gate, and still assert zero
    third-party processors while eight ceremonies shipped prompts to a
    US-hosted model every night. The omission was structural, not clerical:
    nothing under `files/anatomy/agents/` was ever asked.

    WHY `<name>/agent.yml` AND NOT `<name>.yml`. Both exist — the directory
    form is the AgentKit definition, the flat file is the profile
    `pulse-run-agent.sh` reads — and today it is the FLAT one that runs. The
    record still belongs to the directory form: it is validated by
    `state/schema/agent.schema.yaml` (the flat file is validated by nothing),
    and it is keyed to the agent's identity rather than to whichever harness
    currently invokes it, so it survives the spine cutover instead of being
    rewritten by it. The record describes the ceremony's processing under
    EITHER runtime; that is stated in each block's notes.

    id convention: `agent_<slug>`, beside `svc_` and `app_`.
    """
    import yaml

    d = pathlib.Path(agents_dir)
    out: list[dict] = []
    if not d.is_dir():
        return out
    for entry in sorted(d.iterdir()):
        manifest = entry / "agent.yml"
        if not (entry.is_dir() and manifest.is_file()):
            continue
        try:
            m = yaml.safe_load(manifest.read_text()) or {}
        except yaml.YAMLError:
            continue
        if not isinstance(m, dict):
            continue
        gdpr = m.get("gdpr")
        if not gdpr:
            continue
        slug = m.get("name") or entry.name
        out.append(
            gdpr_block_to_record(
                gdpr,
                record_id=f"agent_{slug}",
                slug=str(slug),
                stack=None,
                tier="agent",
                display_name=m.get("name"),
                source_plugin=f"agents/{entry.name}/agent.yml",
            )
        )
    out.sort(key=lambda r: r["id"])
    return out


def all_records(repo_root: str | pathlib.Path) -> list[dict]:
    """Tier-1 + Tier-2 + agent records, the full Article-30 inventory."""
    repo = pathlib.Path(repo_root)
    recs = records_from_plugins(repo / "files/anatomy/plugins")
    recs += records_from_app_manifests(repo / "apps")
    recs += records_from_agents(repo / "files/anatomy/agents")
    return recs
