---
# ==============================================================================
# GIT - global configuration (user.name, user.email)
# ==============================================================================

- name: "[Git] Configure user.name"
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  when: git_user_name | default('') | length > 0

- name: "[Git] Configure user.email"
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  when: git_user_email | default('') | length > 0
