---
- name: Check if .osx script exists.
  ansible.builtin.stat:
    path: "{{ osx_script.split()[0] | expanduser }}"
  register: osx_script_stat

- name: Run .osx dotfiles.
  ansible.builtin.command: "{{ osx_script }}"
  changed_when: false
  when: osx_script_stat.stat.exists
