#!/usr/bin/env python3
"""Emit the KEAP recall-query set from the estate's SKILLS.md trigger lines.

KEAP owns the recall MACHINERY; nOS owns the EXPECTATIONS. Every
`docs/systems/<svc>/SKILLS.md` already states them: each `## <skill>` heading
carries a `**Trigger:**` line of natural-language phrases. Those phrases are
literally query -> expected-winner pairs, so this tool transcribes them into
KEAP's recall fixture shape instead of inventing a second source of truth.

Output shape (matches KEAP e2e/fixtures/selfmodel-recall.json):

    { "comment": "...", "k": 5, "cases": [ {q, expect, forbid}, ... ] }

Per case:
  q       one trigger phrase, verbatim apart from `[placeholder]` de-bracketing
  expect  ["title:<skill>", "node:nos.<stack>.<system>"] — the skill card and
          the system that owns it must win the query
  forbid  ["node:nos", "node:nos.<stack>"] — the ancestors. A stack node or the
          root outranking the specific skill its own query names IS the
          `_stack.md` failure class this gate exists to catch.

Two systems can advertise the same phrase ("list users" is both an Authentik
and a Nextcloud trigger). Contradictory cases would be unfalsifiable, so
identical queries are MERGED: expect is the union of every claimed winner,
forbid the union of the ancestors minus anything that is itself expected.

Usage:
  tools/keap-recall-queries.py                 # write the default path
  tools/keap-recall-queries.py --out <path>
  tools/keap-recall-queries.py --check         # exit 1 if committed file stale

stdlib only, deterministic: same tree in, byte-identical file out.
"""

from __future__ import annotations

import json
import re
import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SYSTEMS_DIR = REPO / "docs" / "systems"
MANIFEST_PATH = REPO / "state" / "manifest.yml"
# The path KEAP's recall gate actually reads (`files/anatomy/cortex/docs/specs/
# recall-gate.md` §6: "read where nOS keeps it — ../nOS/tests/fixtures/
# selfmodel-recall.json"). The former default (state/keap-selfmodel-recall.json)
# has never existed on disk, so `--check` compared the tree against nothing and
# a plain run wrote a file no consumer opened.
DEFAULT_OUT = REPO / "tests" / "fixtures" / "selfmodel-recall.json"

K = 5

# Must match keap_selfmodel_gen.HOST_STACK — the bucket a manifest row with
# `stack: null` (a host-native organ) is modelled under.
HOST_STACK = "host"

COMMENT = (
    "Recall gate query set for the nOS self-model. GENERATED by "
    "tools/keap-recall-queries.py from the '**Trigger:**' lines in "
    "docs/systems/<svc>/SKILLS.md — do not hand-edit; edit the SKILLS.md and "
    "regenerate. Each case asserts MEANING, not length: the named skill card "
    "and the system node that owns it must win the query. 'node:<id>' names a "
    "taxonomy node; 'title:<t>' names a card by title (fs-sync ids are "
    "content-addressed, titles are the stable handle). The forbid lists encode "
    "the _stack.md failure class: a stack node or the root must never beat the "
    "specific system or skill its query names. Where two systems advertise the "
    "same trigger phrase the cases are merged, so expect may name more than "
    "one winner. Services whose manifest install_flag resolves false in "
    "default.config.yml alone (the stock install; the operator's config.yml "
    "overlay is deliberately NOT read, so this committed benchmark is "
    "reproducible in CI) are SKIPPED: the removal ladder takes a parked "
    "service's cards out of the corpus, and its triggers leave the benchmark "
    "with them."
)

# `## <skill>` headings that are documentation sections, not callable skills.
# They carry no Trigger line anyway; listed so the intent is explicit.
NON_SKILL_HEADINGS = {"authentication", "notes", "conventions", "errors"}

HEADING_RE = re.compile(r"^##\s+(?P<name>\S.*?)\s*$")
TRIGGER_RE = re.compile(r"^\s*\*\*Trigger:\*\*\s*(?P<body>.+?)\s*$")
QUOTED_RE = re.compile(r"[\"“]([^\"”]+)[\"”]")
MANIFEST_ID_RE = re.compile(r"^  - id:\s*(?P<id>\S+)\s*$")
MANIFEST_STACK_RE = re.compile(r"^    stack:\s*(?P<stack>\S+)\s*$")
MANIFEST_FLAG_RE = re.compile(r"^    install_flag:\s*(?P<flag>\S+)\s*$")
# Enablement is config, not manifest: the manifest is the full catalog
# (a parked service keeps its row), default.config.yml declares every flag's
# default.
#
# ONLY default.config.yml, deliberately — NOT the operator's config.yml overlay
# (2026-09-05). This tool's sole output is tests/fixtures/selfmodel-recall.json,
# a COMMITTED, CI-GATED artifact: test_selfmodel_recall asserts committed ==
# build(). config.yml is gitignored, so CI resolves flags from defaults alone;
# a fixture built with the operator's overlay (539 cases) can NEVER equal the
# defaults-only build CI produces (466), which is exactly the red this comment
# was written under. The committed benchmark is the STOCK install — reproducible
# by CI, a fresh clone, and any other operator — never one machine's private
# on/off set.
CONFIG_PATHS = (REPO / "default.config.yml",)
INSTALL_RE = re.compile(r"^(?P<flag>install_[a-z0-9_]+):\s*(?P<val>true|false)\b")


def slugify(value: str) -> str:
    """KEAP's slug rule, ported from files/anatomy/face/src/lib/security/uid.ts.

    NFKD, strip combining marks, lowercase, every run of non-[a-z0-9] collapses
    to a single '-', trimmed. KEAP additionally requires a LETTER first, so a
    leading digit run is trimmed too.
    """
    decomposed = unicodedata.normalize("NFKD", value)
    stripped = "".join(ch for ch in decomposed if not unicodedata.combining(ch))
    slug = re.sub(r"[^a-z0-9]+", "-", stripped.lower()).strip("-")
    return re.sub(r"^[0-9-]+", "", slug)


def join_key(value: str) -> str:
    """Separator-insensitive join key: `home-assistant` == `homeassistant`."""
    return re.sub(r"[^a-z0-9]", "", value.lower())


def load_manifest_stacks() -> dict[str, tuple[str, str]]:
    """id-join-key -> (slugified id, stack slug). Line-scanned; stdlib has no YAML.

    state/manifest.yml is a flat two-space list of service mappings, so a
    targeted scan is sufficient and keeps this tool dependency-free.

    `stack: null` is a REAL bucket, not a missing value. The host-native organs
    (pulse, wing, bone, cortex, hermes, openclaw, opencode, backup, backrest,
    alloy, tailscale, iiab-terminal) run outside every compose project, and
    keap_selfmodel_gen.build_slug_model buckets them under HOST_STACK — the node
    genuinely is `nos.host.pulse`. Dropping them here (as this tool did until
    2026-07-26) silently deleted 140 of 593 recall cases: every trigger the
    branch had just authored for those organs, leaving a benchmark that could
    not catch the router answering `node:nos` for "is Pulse running". The
    default below mirrors the generator's `s.get("stack") or HOST_STACK`, so a
    row with no `stack:` key at all lands in the same bucket for the same
    reason.
    """
    services: dict[str, tuple[str, str]] = {}
    current: str | None = None
    for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines():
        m = MANIFEST_ID_RE.match(line)
        if m:
            current = m.group("id")
            services[join_key(current)] = (slugify(current), HOST_STACK)
            continue
        m = MANIFEST_STACK_RE.match(line)
        if m and current is not None:
            stack = m.group("stack")
            if stack in ("null", "~"):
                continue  # keep the HOST_STACK default seeded above
            key = join_key(current)
            services[key] = (services[key][0], slugify(stack))
    return services


def load_install_flags() -> dict[str, bool]:
    """install flag -> resolved value (default.config.yml only; see CONFIG_PATHS)."""
    flags: dict[str, bool] = {}
    for cfg in CONFIG_PATHS:
        if not cfg.is_file():
            continue
        for line in cfg.read_text(encoding="utf-8").splitlines():
            m = INSTALL_RE.match(line)
            if m:
                flags[m.group("flag")] = m.group("val") == "true"
    return flags


def load_manifest_flags() -> dict[str, str]:
    """id-join-key -> install_flag name, only for rows that declare one.

    Host-native organs declare no install_flag and are always kept — the
    host-organ regression (see test_recall_queries_host_organs.py) must stay
    impossible to reintroduce through this path.
    """
    out: dict[str, str] = {}
    current: str | None = None
    for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines():
        m = MANIFEST_ID_RE.match(line)
        if m:
            current = m.group("id")
            continue
        m = MANIFEST_FLAG_RE.match(line)
        if m and current is not None:
            out[join_key(current)] = m.group("flag")
    return out


def normalize_phrase(phrase: str) -> str:
    """Trigger phrase -> query string.

    `"save [file] to cloud"` documents a slot, but a recall query is real text,
    so the brackets are dropped and the placeholder word kept.
    """
    text = phrase.replace("[", "").replace("]", "")
    return re.sub(r"\s+", " ", text).strip()


def parse_skills(path: Path) -> list[tuple[str, list[str]]]:
    """[(skill name, [query, ...]), ...] in file order."""
    out: list[tuple[str, list[str]]] = []
    heading: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        m = HEADING_RE.match(line)
        if m:
            heading = m.group("name")
            continue
        m = TRIGGER_RE.match(line)
        if not m or heading is None:
            continue
        if heading.lower() in NON_SKILL_HEADINGS:
            continue
        # Only QUOTED phrases are queries. An unquoted Trigger body is prose,
        # not natural language a user would type — two skills are marked
        # "(internal — used by playbook ...)" and must not become recall cases.
        raw = QUOTED_RE.findall(m.group("body"))
        queries = [q for q in (normalize_phrase(p) for p in raw) if q]
        if queries:
            out.append((heading, queries))
    return out


def build() -> dict:
    stacks = load_manifest_stacks()
    flags = load_install_flags()
    manifest_flags = load_manifest_flags()
    # q -> {"expect": set, "forbid": set}
    cases: dict[str, dict[str, set[str]]] = {}
    unmatched: list[str] = []
    disabled: list[str] = []

    for skills_file in sorted(SYSTEMS_DIR.glob("*/SKILLS.md")):
        svc_dir = skills_file.parent.name
        entry = stacks.get(join_key(svc_dir))
        if entry is None:
            # The only honest reason to drop a documented system: no manifest row
            # exists for it at all. A row that HAS no stack is not that case.
            unmatched.append(svc_dir)
            continue
        # A DISABLED service leaves the benchmark WITH its cards. The removal
        # ladder takes a parked service's skill cards out of the corpus, so its
        # trigger phrases have no winner to find — keeping them measured what
        # the estate deliberately removed (2026-09-05: 18 erpnext/superset
        # cases regressing against user notes that took over their semantic
        # space). install_flag-less rows (host organs) are always kept.
        flag = manifest_flags.get(join_key(svc_dir))
        if flag is not None and flags.get(flag) is False:
            disabled.append(svc_dir)
            continue
        svc_slug, stack_slug = entry
        node = f"nos.{stack_slug}.{svc_slug}"
        ancestors = {"node:nos", f"node:nos.{stack_slug}"}

        for skill, queries in parse_skills(skills_file):
            for q in queries:
                bucket = cases.setdefault(q, {"expect": set(), "forbid": set()})
                bucket["expect"].add(f"title:{skill}")
                bucket["expect"].add(f"node:{node}")
                bucket["forbid"] |= ancestors

    if unmatched:
        print(
            "WARN: no manifest service (or no stack) for "
            + ", ".join(sorted(unmatched)),
            file=sys.stderr,
        )
    if disabled:
        # Not a WARN: this is the designed behavior, said out loud (no silent caps).
        print(
            "skipped (install flag off): " + ", ".join(sorted(disabled)),
            file=sys.stderr,
        )

    out_cases = []
    for q in sorted(cases):
        expect = cases[q]["expect"]
        forbid = cases[q]["forbid"] - expect
        out_cases.append(
            {
                "q": q,
                "expect": sorted(expect),
                "forbid": sorted(forbid),
            }
        )
    return {"comment": COMMENT, "k": K, "cases": out_cases}


def render(doc: dict) -> str:
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    out_path = DEFAULT_OUT
    if "--out" in argv:
        i = argv.index("--out")
        if i + 1 >= len(argv):
            print("--out needs a path", file=sys.stderr)
            return 2
        out_path = Path(argv[i + 1])
        if not out_path.is_absolute():
            out_path = (REPO / out_path).resolve()

    if not SYSTEMS_DIR.is_dir():
        print(f"missing {SYSTEMS_DIR}", file=sys.stderr)
        return 2
    if not MANIFEST_PATH.is_file():
        print(f"missing {MANIFEST_PATH}", file=sys.stderr)
        return 2

    doc = render(build())
    committed = out_path.read_text(encoding="utf-8") if out_path.exists() else None

    if check:
        if committed != doc:
            print(
                f"STALE: {out_path} does not match docs/systems/*/SKILLS.md — "
                "run tools/keap-recall-queries.py and commit",
                file=sys.stderr,
            )
            return 1
        print(f"OK: recall set fresh ({doc.count(chr(10))} lines)")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(doc, encoding="utf-8")
    n = len(json.loads(doc)["cases"])
    print(f"wrote {out_path} ({n} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
