#!/usr/bin/env python3
"""ADR-0001 Phase 1 — regenerate the OpenTofu Authentik service registry.

Reads the SAME source of truth the imperative blueprint uses — the per-plugin
`authentik:` blocks aggregated by load_plugins.run_aggregators into
authentik-base.inputs.clients — and writes a flat, data-driven registry that
the tfvars template iterates into `var.authentik_services` (for_each).

This is NOT a YAML→HCL code generator (ADR-0001 §9 trap): the HCL is a single
hand-authored `for_each` module; this only refreshes the DATA list. Add a
plugin → re-run this → it appears in tofu. Run whenever plugin authentik:
blocks change:

    python3 tools/tofu-authentik-gen-registry.py

Writes state/tofu-authentik-services.yml (committed; values stay as Jinja
strings — resolved at playbook time by the tfvars template).
"""
from __future__ import annotations

import pathlib
import sys

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "files/anatomy"))
from module_utils import load_plugins  # noqa: E402

OUT = REPO / "state" / "tofu-authentik-services.yml"


def main() -> int:
    plugins = load_plugins.discover(REPO / "files/anatomy/plugins")
    load_plugins.run_aggregators(plugins)  # NO template_vars — keep values as Jinja
    ab = {p.name: p for p in plugins}.get("authentik-base")
    if ab is None:
        print("FAIL: authentik-base plugin not discovered", file=sys.stderr)
        return 2

    services = []
    for c in ab.inputs.get("clients", []):
        slug = c.get("slug")
        if not slug:
            continue
        mode = c.get("mode") or c.get("provider_type")
        # external_host / launch_url carry the Jinja domain expr; keep verbatim.
        ext = c.get("external_host") or c.get("launch_url") or ""
        entry = {
            "slug": slug,
            "name": c.get("name") or slug,
            "mode": mode,                       # native_oidc | forward_auth | header_oidc
            "tier": c.get("tier", 2),
            "external_host": ext,
            "client_id": c.get("client_id") or f"nos-{slug}",
        }
        if mode == "native_oidc":
            entry["client_secret"] = c.get("client_secret") or ""
            entry["redirect_uris"] = c.get("redirect_uris") or []
        services.append(entry)

    services.sort(key=lambda e: e["slug"])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as fh:
        fh.write("# GENERATED by tools/tofu-authentik-gen-registry.py from the\n")
        fh.write("# aggregated per-plugin authentik: blocks (ADR-0001 Phase 1).\n")
        fh.write("# Data only — the tfvars template resolves the Jinja + the\n")
        fh.write("# for_each module in terraform/authentik/services.tf consumes it.\n")
        fh.write("# Regenerate when plugin authentik: blocks change. Committed.\n")
        yaml.safe_dump({"tofu_authentik_services": services}, fh,
                       sort_keys=False, default_flow_style=False, width=200)
    print(f"wrote {len(services)} services -> {OUT.relative_to(REPO)}")
    from collections import Counter
    print("modes:", dict(Counter(s["mode"] for s in services)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
