#!/usr/bin/env python3
"""ADR-0001 Phase 1 — regenerate the OpenTofu Authentik service registry.

Reads the SAME source of truth the imperative blueprint uses — the per-plugin
`authentik:` blocks aggregated by load_plugins.run_aggregators into
authentik-base.inputs.clients — and writes a flat, data-driven registry that
the tfvars template iterates into `var.authentik_services` (for_each).

This is NOT a YAML→HCL code generator (ADR-0001 §9 trap): the HCL is a single
hand-authored `for_each` module; this only refreshes the DATA list. Add a
plugin → re-run this → it appears in tofu. Run whenever plugin authentik:
blocks change:

    python3 tools/tofu-authentik-gen-registry.py

Writes state/tofu-authentik-services.yml (committed; values stay as Jinja
strings — resolved at playbook time by the tfvars template).
"""
from __future__ import annotations

import pathlib
import sys

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "files/anatomy"))
from module_utils import load_plugins  # noqa: E402

OUT = REPO / "state" / "tofu-authentik-services.yml"


def _load_app_manifests() -> list[dict]:
    """Tier-2 apps/<name>.yml harvest — mirrors nos_plugin_loader.py (X.3).

    The live loader passes app_manifests to run_aggregators, so the blueprint
    path always covered Tier-2 authentik: blocks. This generator originally
    didn't — blank #3 (engine=tofu) left documenso/roundcube/twofauth with NO
    provider at all (404 at the outpost): the blueprint render is a no-op
    under tofu and the registry was Tier-1-only. Same skip rules as the
    loader: `_`-prefixed and `.draft` files ignored, malformed files skipped.
    """
    manifests: list[dict] = []
    apps_root = REPO / "apps"
    if not apps_root.is_dir():
        return manifests
    for app_yml in sorted(apps_root.iterdir()):
        name = app_yml.name
        if not (name.endswith(".yml") or name.endswith(".yaml")):
            continue
        if name.startswith("_") or ".draft" in name:
            continue
        try:
            parsed = yaml.safe_load(app_yml.read_text()) or {}
        except Exception:                                      # noqa: BLE001
            continue
        if isinstance(parsed, dict):
            manifests.append(parsed)
    return manifests


def main() -> int:
    plugins = load_plugins.discover(REPO / "files/anatomy/plugins")
    # NO template_vars — keep values as Jinja
    load_plugins.run_aggregators(plugins, app_manifests=_load_app_manifests())
    ab = {p.name: p for p in plugins}.get("authentik-base")
    if ab is None:
        print("FAIL: authentik-base plugin not discovered", file=sys.stderr)
        return 2

    services = []
    seen_slugs: set[str] = set()
    for c in ab.inputs.get("clients", []):
        slug = c.get("slug")
        if not slug:
            continue
        # Dedupe by slug — a service can appear via BOTH a Tier-1 plugin and a
        # Tier-2 app manifest (qdrant does). Aggregation order is plugins
        # first, so the plugin block wins; the tfvars map would otherwise
        # silently keep the LAST entry.
        if slug in seen_slugs:
            continue
        seen_slugs.add(slug)
        mode = c.get("mode") or c.get("provider_type")
        # external_host / launch_url carry the Jinja domain expr; keep verbatim.
        ext = c.get("external_host") or c.get("launch_url") or ""
        entry = {
            "slug": slug,
            "name": c.get("name") or slug,
            "mode": mode,                       # native_oidc | forward_auth | header_oidc
            "tier": c.get("tier", 2),
            "external_host": ext,
            "client_id": c.get("client_id") or f"nos-{slug}",
        }
        if mode == "native_oidc":
            entry["client_secret"] = c.get("client_secret") or ""
            entry["redirect_uris"] = c.get("redirect_uris") or []
        services.append(entry)

    services.sort(key=lambda e: e["slug"])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as fh:
        fh.write("# GENERATED by tools/tofu-authentik-gen-registry.py from the\n")
        fh.write("# aggregated per-plugin authentik: blocks (ADR-0001 Phase 1).\n")
        fh.write("# Data only — the tfvars template resolves the Jinja + the\n")
        fh.write("# for_each module in terraform/authentik/services.tf consumes it.\n")
        fh.write("# Regenerate when plugin authentik: blocks change. Committed.\n")
        yaml.safe_dump({"tofu_authentik_services": services}, fh,
                       sort_keys=False, default_flow_style=False, width=200)
    print(f"wrote {len(services)} services -> {OUT.relative_to(REPO)}")
    from collections import Counter
    print("modes:", dict(Counter(s["mode"] for s in services)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
