#!/usr/bin/env bash
# tools/tofu-authentik-adopt.sh — ADR-0001 Phase 1 one-time tenant adoption.
#
# Bootstraps OpenTofu HCL + state for the ENTIRE live Authentik tenant so the
# eventual `authentik_engine: tofu` flip plans as a NO-OP (the destroy guard in
# tasks/tofu-authentik.yml refuses apply until it is). This is NOT the steady-
# state authoring path (that is hand-authored module calls per ADR-0001 §9) —
# it is the standard `import` + `-generate-config-out` adoption tool you run
# ONCE against an existing tenant, then refactor the generated flat resources
# toward modules/nos-authentik-app over time.
#
# It writes:
#   terraform/authentik/imports.generated.tf   — import {} blocks (one per live obj)
#   terraform/authentik/generated.tf           — HCL generated from live state
# both gitignored until reviewed; commit after you've refactored + proven no-op.
#
# SAFE: import + plan only. Never applies. Never mutates the tenant.
#
# Usage:
#   tools/tofu-authentik-adopt.sh            # generate import blocks + config
#   tools/tofu-authentik-adopt.sh --plan     # + show the resulting plan summary
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$REPO_ROOT/terraform/authentik"
SECRETS="${HOME}/.nos/secrets.yml"

command -v tofu >/dev/null || { echo "[adopt] tofu not on PATH — install OpenTofu"; exit 2; }
[ -f "$SECRETS" ] || { echo "[adopt] $SECRETS not found"; exit 2; }

TOKEN="$(grep '^authentik_bootstrap_token' "$SECRETS" | awk '{print $2}' | tr -d '"')"
PORT="$(grep '^authentik_port' "$REPO_ROOT/default.config.yml" | head -1 | awk '{print $2}' | sed 's/#.*//' | tr -d ' ' || echo 9000)"
API="http://127.0.0.1:${PORT}/api/v3"
auth=(-H "Authorization: Bearer ${TOKEN}")

echo "[adopt] tenant API: $API"
curl -fsS -o /dev/null "${auth[@]}" "$API/core/users/me/" || { echo "[adopt] token auth failed against $API"; exit 2; }

IMP="$TF_DIR/imports.generated.tf"
: > "$IMP"
echo "# GENERATED by tools/tofu-authentik-adopt.sh — import blocks for tenant adoption." >> "$IMP"
echo "# Review + refactor toward modules/nos-authentik-app, then delete this file." >> "$IMP"

emit() {  # <tf_type> <tf_addr_suffix> <import_id> <name_for_comment>
  cat >> "$IMP" <<EOF

import {
  to = ${1}.${2}
  id = "${3}"
}
EOF
}

# embedded outpost id — needed to compose the attachment import ids below.
# Import id format for authentik_outpost_provider_attachment is
# "<outpost_uuid>:<provider_pk>" (confirmed from the live terraform.tfstate:
# all attachments serialize as id = "<outpost_uuid>:<provider_pk>").
echo "[adopt] resolving embedded outpost id..."
OUTPOST_ID="$(curl -fsS "${auth[@]}" "$API/outposts/instances/?page_size=200" \
  | python3 -c "import json,sys
for o in json.load(sys.stdin)['results']:
    if o.get('name')=='authentik Embedded Outpost':
        print(o['pk']); break")"
[ -n "$OUTPOST_ID" ] || { echo "[adopt] could not resolve embedded outpost id"; exit 2; }

# proxy providers + their embedded-outpost attachments. Every proxy provider
# (forward_auth/header_oidc) MUST be bound to the embedded outpost or forward
# auth 404s — so each proxy provider yields TWO import blocks: the provider
# and its attachment (id "<outpost_uuid>:<provider_pk>").
echo "[adopt] enumerating proxy providers + outpost attachments..."
curl -fsS "${auth[@]}" "$API/providers/proxy/?page_size=200" \
  | OUTPOST_ID="$OUTPOST_ID" python3 -c "import json,os,sys,re
op=os.environ['OUTPOST_ID']
for p in json.load(sys.stdin)['results']:
    a=re.sub(r'[^a-z0-9_]','_',p['name'].lower())
    print(f\"authentik_provider_proxy adopt_{a} {p['pk']}\")
    print(f\"authentik_outpost_provider_attachment adopt_attach_{a} {op}:{p['pk']}\")" \
  | while read -r t a id; do emit "$t" "$a" "$id" "$a"; done

# oauth2 providers
echo "[adopt] enumerating oauth2 providers..."
curl -fsS "${auth[@]}" "$API/providers/oauth2/?page_size=200" \
  | python3 -c "import json,sys,re
for p in json.load(sys.stdin)['results']:
    a=re.sub(r'[^a-z0-9_]','_',p['name'].lower())
    print(f\"authentik_provider_oauth2 adopt_{a} {p['pk']}\")" \
  | while read -r t a id; do emit "$t" "$a" "$id" "$a"; done

# applications (import by slug)
echo "[adopt] enumerating applications..."
curl -fsS "${auth[@]}" "$API/core/applications/?page_size=200" \
  | python3 -c "import json,sys,re
for app in json.load(sys.stdin)['results']:
    a=re.sub(r'[^a-z0-9_]','_',app['slug'].lower())
    print(f\"authentik_application adopt_app_{a} {app['slug']}\")" \
  | while read -r t a id; do emit "$t" "$a" "$id" "$a"; done

N="$(grep -c '^import {' "$IMP" || true)"
echo "[adopt] wrote $N import blocks → $IMP"

echo "[adopt] generating HCL from live state (tofu plan -generate-config-out)..."
cd "$TF_DIR"
tofu plan -input=false -generate-config-out=generated.tf -no-color >/tmp/adopt-plan.txt 2>&1 || true
echo "[adopt] generated.tf: $(wc -l < generated.tf 2>/dev/null || echo 0) lines"
grep -E "Plan:|to import|generated configuration" /tmp/adopt-plan.txt | tail -5 || true

cat <<'NEXT'

[adopt] NEXT STEPS (operator):
  1. Review terraform/authentik/generated.tf — refactor flat resources toward
     module "nos-authentik-app" calls where they fit; keep raw for the exotic.
  2. tofu plan  — iterate on attributes until it reads NO-OP (0 to add/change/
     destroy). Timings/redirect_uri_type/ssl_validation are the usual deltas.
  3. ONLY when plan is no-op: set authentik_engine: "tofu" in config.yml and run
     `ansible-playbook main.yml --tags tofu-authentik -e manage_authentik_with_tofu=true`.
     The destroy guard refuses apply if ANY destroy remains.
  4. Commit generated.tf + imports.generated.tf once reviewed (they're gitignored
     until then). Then delete the imperative 10-oidc-apps render path.
NEXT
